const express = require("express")
const router = express.Router()
const upload = require("../../public/config/uploads")
const serviceController = require("../controllers/serviceController")
router.get('/services/get_list_service',getListService)
router.post('/services/add_service',upload.single("images"),addService)
router.put('/services/update_service/:id',upload.single("images"),updateService)
router.get('/services/getListServiceByCategory/:id_category',getListServiceByCategory)
router.get('/getGroupedServices',getGroupedServices)